<?php

/**
 * @file
 * Contains hero_banner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hero_banner_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hero_banner module.
    case 'help.page.hero_banner':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hero_banner_theme() {
  return [
    'hero_banner' => [
      'render element' => 'children',
    ],
  ];
}

 /**
 * Implements hook_page_attachments().
 */
function islandora_repository_reports_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'hero_banner/hero_banner_css';
}
